### ISSUE TITLE
Application icon

### ISSUE THREAD

**Issue by PlugaruT** [PlugaruT/wingpanel-monitor#1]
The application needs an icon so that I could publich it to AppCenter

**Comment by PlugaruT** [comment]
@Fatih20 are you available to help me with this? 
You also helped me with the other app I have

**Comment by Fatih20** [comment]
Sure. I'll look into it.

**Comment by Fatih20** [comment]
@PlugaruT I can't make the icon if I don't know what the heck this thing does and what the icon is used for, tho.

**Comment by PlugaruT** [comment]
It's basically [this indicator](https://github.com/PlugaruT/wingpanel-indicator-sys-monitor) but as an application so that I could publish to AppCenter.

**Comment by Fatih20** [comment]
Would the app be shown on the dock below when it's running or is it some sort of a daemon?

**Comment by PlugaruT** [comment]
The app basically will be used to configure what the indicator will show. It's more like a configurator for the indicator. When open, there will be an icon shown in Plank, but the indicator can run without the application being open.

**Comment by Fatih20** [comment]
I'll start drawing concept.

**Comment by Fatih20** [comment]
![con github PlugaruT wingpanel-monitor](https://user-images.githubusercontent.com/51940383/73586994-ff533a00-44e7-11ea-93f1-c689cbb9263d.png)
What do you think? I want to make sure you're okay with the initial concept before pixel fitting them.

**Comment by PlugaruT** [comment]
What do you say if we drop the fan in the middle?

**Comment by Fatih20** [comment]
Um, no? The whole icon is supposed to represent a computer. I could drop it and try to make a computer without it but it would look to much like a server. Furthermore, the fan is there to showcase one of the feature of this app which is to show temperature, which is tied to other feature of the app, which is to show CPU and RAM usage. 
What reason do you have to get rid of the fans?

**Comment by PlugaruT** [comment]
Oh, I see now 😅
Well, now that you've explained it to me, it make sense. Overall I like the icon. Good job 👍

**Comment by Fatih20** [comment]
Thanks! I'll move forward with it.

**Comment by PlugaruT** [comment]
Fixed in #3
