### ISSUE TITLE
Re-design network indicator

### ISSUE THREAD

**Issue by lucsoft** [PlugaruT/wingpanel-monitor#10]
Nice Work!

But the icons look a bit off
Hope i can help you with my "design"

before
![image](https://user-images.githubusercontent.com/11093382/76254833-6c778f00-624d-11ea-9b06-b3af77c9a5cc.png)
after
![image](https://user-images.githubusercontent.com/11093382/76254797-5f5aa000-624d-11ea-89d1-71805e8094c6.png)

**Comment by PlugaruT** [comment]
Thank you. I have a fix for the alignment but, regarding the redesign of network indicator, I have to think how to do it.

**Comment by nguyennghia9222** [comment]
Hi PlugaruT,
I really like your indicator, but I have small problem with icons. I just followed the build guideline
![Screenshot from 2020-03-11 09 32 55](https://user-images.githubusercontent.com/26781069/76376769-bced0a80-637b-11ea-822b-80df03ceaf8f.png)
Could you help me to fix this issue? Thanks

**Comment by lucsoft** [comment]
have you installed all?

**Comment by nguyennghia9222** [comment]
I did build and install by commands:
```
meson build --prefix=/usr
cd build
ninja
```
`sudo ninja install`
Did I miss something?

**Comment by PlugaruT** [comment]
Yes, there is a problem with the icons, i am trying to fix it.

**Comment by PlugaruT** [comment]
@nguyennghia9222 this was fixed in #11

**Comment by PlugaruT** [comment]
@lucsoft, what do you think about the new network indicator?

**Comment by nguyennghia9222** [comment]
Thank @PlugaruT ,
Love it :dancing_men: :
![Screenshot from 2020-03-13 10 24 38](https://user-images.githubusercontent.com/26781069/76586964-015fde00-6515-11ea-8969-0c950d0d7ac3.png)

**Comment by lucsoft** [comment]
It looks better for sure but its still really big, its just a status 

![image](https://user-images.githubusercontent.com/11093382/76602790-f9e80700-650b-11ea-8ae6-76eedcaf305f.png)

**Comment by PlugaruT** [comment]
@lucsoft the new indicator is on #12

**Comment by casasfernando** [comment]
> It looks better for sure but its still really big, its just a status
> 
> ![image](https://user-images.githubusercontent.com/11093382/76602790-f9e80700-650b-11ea-8ae6-76eedcaf305f.png)

@lucsoft did you actually managed to change the code to make it look like this or is just a design idea?
I really like how your proposal looks and I'm trying to make it look like that but without success.

Thanks.

**Comment by casasfernando** [comment]
This is as close as I could get so far:
![image](https://user-images.githubusercontent.com/15861819/113910141-ca700080-97d8-11eb-8bb7-ac608ddc4add.png)

Still not looking as compact as yours and I need to change the icons (not sure yet if I will do it tough).

**Comment by lucsoft** [comment]
no this was made with figma 
you need 4 text fields

Somewhat like this:
Icon AlignRight AlignLeft
Icon AlignRight AlignLeft

**Comment by casasfernando** [comment]
Thanks for clarifying. That explains why it looks so good.
Indeed, I'm working on it, still didn't decide if I will use on icon like in the screenshot above (different icon tough) or two like in your design. I guess I will try both and decide.
