### ISSUE TITLE
ERROR: Neither directory contains a build file meson.build.

### ISSUE THREAD

**Issue by gkpiccoli** [PlugaruT/wingpanel-monitor#19]
Hi, i'm new on linux world, i'm trying to install the wingpanel, but when i write on terminal: meson build --prefix=/usr
Show this:
ERROR: Neither directory contains a build file meson.build.
what i do? Thanks for the support n sorry for bad english!
elementary OS 5.1.7 Hera
![Captura de tela de 2020-09-15 13-41-48](https://user-images.githubusercontent.com/70539327/93239576-5c3ef000-f759-11ea-892e-22498a9fdd74.png)

**Comment by PlugaruT** [comment]
You should also clone the repo:
`git clone https://github.com/PlugaruT/wingpanel-monitor.git`
then
`cd wingpane-monitor`
and then do the meson thingie

**Comment by gkpiccoli** [comment]
Thanks for the support! It took me a while, but I did it with your help. Thanks for the support! The doubt is the "cd build" in this case "cd wingpanel-monitor" 
![Captura de tela de 2020-09-15 15-30-44](https://user-images.githubusercontent.com/70539327/93250734-a039f100-f769-11ea-9c9b-012d4834944f.png)
... 
Now its working perfectly.
Thank you so much!!!

**Comment by gkpiccoli** [comment]
![Captura de tela de 2020-09-15 15-42-55](https://user-images.githubusercontent.com/70539327/93251137-29e9be80-f76a-11ea-8a5d-ea10bd601d9f.png)
