### ISSUE TITLE
Please provide a deb package for easier installation

### ISSUE THREAD

**Issue by casasfernando** [PlugaruT/wingpanel-monitor#22]
Thanks for creating this indicator, it's really nice.

Any chance you can provide a deb package to make installation easier and cleaner for end users?
Having to compile the source code requires many dependencies installation and manual steps.
A PPA or a deb package already available in the GitHub repo would make things much easier.

Thanks!

**Comment by PlugaruT** [comment]
Hi, @casasfernando, 
unfortunately, I am no longer using elementary OS and it's hard for me to develop further this widget. 
Ideally, this app should be published in AppCenter, but it was no accepted, you can read more about this in #4 
Not sure what is the state of eOS now... Maybe something have changed.

**Comment by casasfernando** [comment]
Thanks for the reply.
Indeed I went over [#4](https://github.com/PlugaruT/wingpanel-monitor/issues/4) and saw what happened but since I found that the last commit was around 4 months ago, I thought you was still working/maintaining this indicator.

Hopefully someone can take over (I'm not a developer unfortunately) and continue to build on your great work.

Closing the issue. Thanks again.
