### ISSUE TITLE
Change text size

### ISSUE THREAD

**Issue by S8D** [PlugaruT/wingpanel-monitor#35]
How to change the font size of the network speed?
I want to increase the size of the network speed.
Many thanks!

**Comment by vjr** [comment]
FYI, I've submitted a code fix for review here: https://github.com/PlugaruT/wingpanel-monitor/pull/30

And already issue filed here: https://github.com/PlugaruT/wingpanel-monitor/issues/28

You can close this as a duplicate issue.
