### ISSUE TITLE
Add Graphs

### ISSUE THREAD

**Issue by lucsoft** [PlugaruT/wingpanel-monitor#9]
Allow to Change to a Graph view in the style of: 
![image](https://user-images.githubusercontent.com/11093382/76253683-6aaccc00-624b-11ea-8c11-a9eccad3d874.png)

**Comment by andirsun** [comment]
I think this is not the scope of this indicator, there are other apps to achieve this, see: https://appcenter.elementary.io/com.github.stsdc.monitor/
